### ISSUE TITLE
Wrong endpoint in Open API spec

### ISSUE THREAD

**Issue by mattiasmelin** [skolverket/dnp-ss12000-reference-api#13]
https://github.com/skolverket/dnp-ss12000-reference-api/blob/main/src/main/resources/openapi/expose/openapi/openapi.yml#L518

Here it says /logs and that does not match /log in ss12000v2 API specification.
Please correct this.

**Comment by GustafNilstadius** [comment]
Fixed incorrect plural in openapi.yml, now corresponding to SS 12000 standard and previously existing code.
