### ISSUE TITLE
Group membership missing?

### ISSUE THREAD

**Issue by mattiasmelin** [skolverket/dnp-ss12000-reference-api#3]
When looking into [src/main/resources/openapi/expose/openapi/openapi.yml](src/main/resources/openapi/expose/openapi/openapi.yml) and comparing to full ss12000 api specification i am missing the property *groupMemberships* for a Group.

Is this intended?

If so how do we connect an enrolment/person to a group?

**Comment by GustafNilstadius** [comment]
This is a miss in the documentation, openapi.yml. It's not been updated in a while. `groupMemberships` is a member of the `se.skolverket.service.provisioning.provisioningreferenceapi.services.groups.model.Group`. 
  
Tagging the issue as `documentation` as openapi.yml needs improvements and additions for both the expose and ingest services.

**Comment by mattiasmelin** [comment]
@GustafNilstadius It seems like these changes has been lost somehow or am I missing something.

I cannot see these changes in main branch.

**Comment by GustafNilstadius** [comment]
Seems like the changes were lost in a recent sync from the internal code base to the external (this) codebase. Will address immediately! Thanks for noticing.
