### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by joesiltberg** [skolverket/dnp-ss12000-reference-api#6]
Hi!

I was asked by Niklas Leide to ask this question here on GitHub.

I'm wondering in what way the reference implementation is able to detect errors. More specifically:

1. Are the endpoints /log and /statistics implemented?
2. If so, what happens with the information sent there? For instance:
   1. Are log entries and statistics stored in the database?
   2. Is there a way to be notified when an error or warning arrives?
   3. Do certain warnings or errors lead to any actions by the reference implementation (such as attempting to retry something, sending a new notification to the webhook or similar)
  4. Are the numbers in the StatisticsEntry object verified against what would be expected numbers?
3. If a notification can't be sent (e.g. the target URL for the webhook can't be reached) , what happens?
4. If a notification _can_ be sent, but the consuming system doesn't act on it (fails to ask for the changes), or acts incorrectly (asks a question that doesn't retrieve the intended changes), does anything happen?

**Comment by GustafNilstadius** [comment]
This is definitely the place for technical questions! 

1. Yes. It's handled by the `logging` and `statistics` services. 
2. See the source code. 
    2.1. It's stored in the database.
    2.2 Depending on what you mean with "to be notified". The SS12000 API is being notified and the current behavior is to store it in the database. The project is open source and serves as a reference implementation. A solution could be to allow for subscriptions listening to `log` and `statistics` data types, it would be a minor change.  
    2.3 No, all logs and statistic entries are handled the same. The most common cause of a errors are things that won't be fixed with a retry. 
3. No. 
4. There's a built in retry logic. As specified in the SS12000 standard, 3 retries will be done in 5 minutes and after that there's no further attempts and the webhook will not be sent.  
5. If the client receives a webhook and responds with a 2XX response the  webhook has been persisted in a job queue. Multiple retries will be made to honor the webhook, if it can't be processed a error log is reported back (also with multiple retries). In case of a catastrophic failure there's no logic in the reference api to handle it as it's not defined in the standard.

**Comment by joesiltberg** [comment]
Thank you for a quick reply @GustafNilstadius !
